SE Project/Models/Assets.cs
    using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SE_Project.Models
{
    public class Assets
    {
        public string SelectedDropDownItem { get; set; }
    }
    public class HardwareAssets
    {
        [Display(Name = "Serial No.")]
        [Required]
        public string SerialNo { get; set; }
        [Display(Name = "IP Address")]
        public string IpAddress { get; set; }
        [Display(Name = "MAC Address")]
        public string MacAddress { get; set; }
        [Display(Name = "Computer Name")]
        public string ComputerName { get; set; }
        [Display(Name = "Computer Model")]
        public string ComputerModel { get; set; }
        [Display(Name = "Computer OS")]
        public string ComputerOS { get; set; }
        
        [Display(Name = "Equipment Type")]
        [Required]
        public string EquipmentType { get; set; }
    }
    public class Hardware_Ownership
    { 
        [Display(Name = "Serial No.")]
        [Required]
        public string SerialNo { get; set; }

        [Display(Name = "Employee ID")]
        [Required]
        public string EmployeeID { get; set; }
        [Display(Name = "Computer Status")]
        [Required]
        public string ComputerStatus { get; set; }
        [Display(Name = "Condition")]
        [Required]
        public string Condition { get; set; }

    }

    public class Edit_Hardware_Ownership_View
    {

        [Display(Name = "Serial No.")]
        [Required]
        public string SerialNo { get; set; }
        [Display(Name = "IP Address")]
        public string IpAddress { get; set; }
        [Display(Name = "MAC Address")]
        public string MacAddress { get; set; }
        [Display(Name = "Computer Name")]
        public string ComputerName { get; set; }
        [Display(Name = "Computer Model")]
        public string ComputerModel { get; set; }
        [Display(Name = "Computer OS")]
        public string ComputerOS { get; set; }

        [Display(Name = "Equipment Type")]
        [Required]
        public string EquipmentType { get; set; }

        [Display(Name = "Employee ID")]
        [Required]
        public string EmployeeID { get; set; }
        [Display(Name = "Computer Status")]
        [Required]
        public string ComputerStatus { get; set; }
        [Display(Name = "Condition")]
        [Required]
        public string Condition { get; set; }
    }
    public class HardwareViewList
    {
        public string IpAddress { get; set; }
        public string ComputerName { get;set; }
        public string EquipmentType { get; set; }   
        public string FullName { get; set; }    
        public string Office { get; set; }
        public string Department { get; set; }
        public string Condition { get; set; }
        public string ComputerStatus { get; set; }
        public string EmployeeID { get; set; }
    }
    public class SoftwareAssets
    {
        [Display(Name = "Serial No.")]
        [Required]
        public string SerialNo { get; set; }
        [Display(Name = "Software Name")]
        [Required]
        public string SoftwareName { get; set; }
        [Display(Name = "Purchase Date")]
        [Required]
        public DateTime PurchaseDate{ get; set; }
        [Display(Name = "Expiry Date")]
        [Required]
        public DateTime ExpiryDate { get; set; }
        [Display(Name = "Cost")]
        [Required]
        public double Cost { get; set; }
        [Display(Name = "Vendor")]
        [Required]
        public string Vendor { get; set; }
        [Display(Name = "Employee ID")]
        [Required]
        public string EmployeeID { get; set; }
    }

    public class SoftwareViewList
    {
        [Display(Name = "Serial No.")]
        [Required]
        public string SerialNo { get; set; }
        [Display(Name = "Software Name")]
        [Required]
        public string SoftwareName { get; set; }
        [Display(Name = "Purchase Date")]
        [Required]
        public string PurchaseDate { get; set; }
        [Display(Name = "Expiry Date")]
        [Required]
        public string ExpiryDate { get; set; }
        [Display(Name = "Cost")]
        [Required]
        public double Cost { get; set; }
        [Display(Name = "Vendor")]
        [Required]
        public string Vendor { get; set; }
        
        public string FullName { get; set; }
        public string Department { get; set; }
        public string Office { get; set; }
        [Display(Name = "Employee ID")]
        [Required]
        public string EmployeeID { get; set; }
    }

    public class HardwareStatusReportView
    {
        public string computerStatus;
        public int hardwareTotalQty;
    }
    public class EquipmentTypeReportView
    {
        public string equipmentType;
        public int equipmentTotalQty;
    }
}

SE Project/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using SE_Project.Models;

namespace SE_Project.Controllers
{
    public class AssetsController : Controller
    {
        private readonly string connectionString = "Server=LAPTOP-RH67UL1G\\SQLEXPRESS;Database=AssetManagementSystem;User Id=ymsmis;Password=iamking;";

        // GET: Assets
        public ActionResult Index()
        {
            return View();
        }

        // GET: HardwareAssets (Display All)
        public ActionResult GetHardwareAssets()
        {
            List<HardwareViewList> hardwareList = new List<HardwareViewList>();
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sqlQuery = "SELECT C.IpAddress, C.ComputerName, C.EquipmentType, CONCAT(O.FirstName,' ',O.LastName) AS Name, O.Office, O.Department, CO.Condition, CO.ComputerStatus, O.EmployeeID " +
                    "FROM Computer C JOIN Computer_Ownership CO ON C.SerialNo = CO.SerialNo JOIN Ownership O ON O.EmployeeID = CO.EmployeeID";

                using (SqlCommand command = new SqlCommand(sqlQuery, connection))
                {
                    connection.Open();

                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        HardwareViewList ho = new HardwareViewList
                        {
                            IpAddress = reader.IsDBNull(0) ? null : reader.GetString(0),
                            ComputerName = reader.IsDBNull(1) ? null : reader.GetString(1),
                            EquipmentType = reader.IsDBNull(2) ? null : reader.GetString(2),
                            FullName = reader.GetString(3),
                            Office = reader.GetString(4),
                            Department = reader.GetString(5),
                            Condition = reader.GetString(6),
                            ComputerStatus = reader.GetString(7),
                            EmployeeID = reader.GetString(8)
                        };
                        hardwareList.Add(ho);
                    }
                    connection.Close();
                }
            }
            return View(hardwareList);
        }


        //Create Hardware Assets View
        public ActionResult CreateHardwareAssets()
        {
            return View();
        }

        //POST: Create Hardware Assets
        [HttpPost]
        public ActionResult CreateHardwareAssets(HardwareAssets ha)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {
                        string query = "INSERT INTO Computer (SerialNo,IpAddress,MacAddress,ComputerName,ComputerModel,ComputerOS,EquipmentType) VALUES (@property1, @property2,@property3, @property4,@property5,@property6, @property7)";

                        connection.Open();

                        SqlCommand command = new SqlCommand(query, connection);
                        command.Parameters.AddWithValue("@property1", ha.SerialNo);
                        command.Parameters.AddWithValue("@property2", ha.IpAddress ?? (object)DBNull.Value);
                        command.Parameters.AddWithValue("@property3", ha.MacAddress ?? (object)DBNull.Value);
                        command.Parameters.AddWithValue("@property4", ha.ComputerName ?? (object)DBNull.Value);
                        command.Parameters.AddWithValue("@property5", ha.ComputerModel ?? (object)DBNull.Value);
                        command.Parameters.AddWithValue("@property6", ha.ComputerOS ?? (object)DBNull.Value);
                        command.Parameters.AddWithValue("@property7", ha.EquipmentType);
                        // Add more parameters as needed

                        command.ExecuteNonQuery();

                        // Create success message
                        TempData["SuccessMessage"] = "Hardware Asset Registration Successfully.";
                        connection.Close();
                    }
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    return View("Error", new HandleErrorInfo(ex, "Index", "Home"));
                }
            }

            return View(ha);
        }

        //Set Hardware Ownership
        public ActionResult HardwareOwnership()
        {
            // Retrieve the lists from the database
            List<Employee> employeeList = GetEmployeeIDFromDatabase();
            List<HardwareAssets> compList = GetSerialNoFromDatabase();

            ViewBag.EmployeeRecord = new SelectList(employeeList, "EmployeeID", "EmployeeID");
            ViewBag.ComputerRecord = new SelectList(compList, "SerialNo", "SerialNo");

            return View();
        }

        //POST: Set Hardware Ownership
        [HttpPost]
        public ActionResult HardwareOwnership(Hardware_Ownership ho)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {

                        string query = "INSERT INTO Computer_Ownership (SerialNo,EmployeeID,ComputerStatus,Condition) VALUES (@property1, @property2,@property3, @property4)";

                        connection.Open();

                        SqlCommand command = new SqlCommand(query, connection);
                        command.Parameters.AddWithValue("@property1", ho.SerialNo);
                        command.Parameters.AddWithValue("@property2", ho.EmployeeID);
                        command.Parameters.AddWithValue("@property3", ho.ComputerStatus);
                        command.Parameters.AddWithValue("@property4", ho.Condition);

                        command.ExecuteNonQuery();

                        // Create success message
                        TempData["SuccessMessage"] = "Hardware Ownership Registration Successfully.";
                        connection.Close();
                    }

                    return RedirectToAction("Index", "Home");

                }
                catch (SqlException ex)
                {
                    if (ex.Number == 2627) // Error number for primary key violation
                    {
                        // Handle the primary key violation here
                        // You can display an error message to the user or take appropriate action
                    }
                    else
                    {
                        // Handle other SQL exceptions
                    }
                }
                catch (Exception ex)
                {
                    return View("Error", new HandleErrorInfo(ex, "Index", "Home"));
                }
            }

            // Retrieve the lists from the database
            List<Employee> employeeList = GetEmployeeIDFromDatabase();
            List<HardwareAssets> compList = GetSerialNoFromDatabase();

            ViewBag.EmployeeRecord = new SelectList(employeeList, "EmployeeID", "EmployeeID");
            ViewBag.ComputerRecord = new SelectList(compList, "SerialNo", "SerialNo");

            return View(ho);
            
        }
        private List<Employee> GetEmployeeIDFromDatabase()
        {
            List<Employee> employeeList = new List<Employee>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sqlQuery = "SELECT * FROM Ownership WHERE EmployeeID != 'MS-8888'";
                connection.Open();
                using (SqlCommand command = new SqlCommand(sqlQuery, connection))
                {

                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        Employee employee = new Employee
                        {
                            EmployeeID = reader.GetString(0),
                            FirstName = reader.GetString(1),
                            LastName = reader.GetString(2),
                            Office = reader.GetString(3),
                            Department = reader.GetString(4)

                        };

                        employeeList.Add(employee);
                    }

                }
                connection.Close();
            }
            return employeeList;
        }
        private List<HardwareAssets> GetSerialNoFromDatabase()
        {
            List<HardwareAssets> compList = new List<HardwareAssets>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sqlQuery = "SELECT * FROM Computer";

                connection.Open();

                using (SqlCommand command = new SqlCommand(sqlQuery, connection))
                {

                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        HardwareAssets comp = new HardwareAssets
                        {
                            SerialNo = reader.GetString(0),
                            IpAddress = reader.IsDBNull(1) ? null : reader.GetString(1),
                            MacAddress = reader.IsDBNull(2) ? null : reader.GetString(2),
                            ComputerName = reader.IsDBNull(3) ? null : reader.GetString(3),
                            ComputerModel = reader.IsDBNull(4) ? null : reader.GetString(4),
                            ComputerOS = reader.IsDBNull(5) ? null : reader.GetString(5),
                            EquipmentType = reader.GetString(6)
                        };

SE Project/Views/Assets/CreateHardwareAssets.cshtml
@model SE_Project.Models.HardwareAssets

@Html.AntiForgeryToken()

<section class="h-100">
    <div class="container h-100">
        <div class="row justify-content-sm-center h-100">
            <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
                <div class="text-center my-5">
                    <img src="~/Photos/Mazak_logo.png" alt="logo" width="400" />
                </div>
                <div class="card shadow-lg">
                    <div class="card-body p-5">
                        <h1 class="fs-4 card-title fw-bold mb-4">Create Hardware Assets</h1>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @using (Html.BeginForm("CreateHardwareAssets", "Assets", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            <div class="form-group">
                                @Html.LabelFor(model => model.SerialNo, htmlAttributes: new { @class = "control-label mb-2 text-muted" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.SerialNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.SerialNo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.IpAddress, htmlAttributes: new { @class = "control-label mb-2 text-muted" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.IpAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IpAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MacAddress, htmlAttributes: new { @class = "control-label mb-2 text-muted" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.MacAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MacAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ComputerName, htmlAttributes: new { @class = "control-label mb-2 text-muted" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ComputerName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ComputerName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ComputerModel, htmlAttributes: new { @class = "control-label mb-2 text-muted" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ComputerModel, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ComputerModel, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            #region ViewBag
                            List<SelectListItem> createOS = new List<SelectListItem>();
                            createOS.Add(new SelectListItem { Text = "Windows 11 Pro", Value = "Windows 11 Pro" });
                            createOS.Add(new SelectListItem { Text = "Windows 11 Home", Value = "Windows 11 Home" });
                            createOS.Add(new SelectListItem { Text = "Windows 10 Pro", Value = "Windows 10 Pro" });
                            createOS.Add(new SelectListItem { Text = "Windows 10 Home", Value = "Windows 10 Home" });
                            createOS.Add(new SelectListItem { Text = "Windows 8.1 Pro", Value = "Windows 8.1 Pro" });
                            createOS.Add(new SelectListItem { Text = "Windows 7 Pro", Value = "Windows 7 Pro" });
                            createOS.Add(new SelectListItem { Text = "Windows 7 Home", Value = "Windows 7 Home" });
                            createOS.Add(new SelectListItem { Text = "Windows XP", Value = "Windows XP" });
                            createOS.Add(new SelectListItem { Text = "Windows 2000", Value = "Windows 2000" });
                            createOS.Add(new SelectListItem { Text = "Windows Server 2022", Value = "Windows Server 2022" });
                            createOS.Add(new SelectListItem { Text = "Windows Server 2019", Value = "Windows Server 2019" });
                            createOS.Add(new SelectListItem { Text = "Windows Server 2016", Value = "Windows Server 2016" });
                            createOS.Add(new SelectListItem { Text = "Windows Server 2012 R2", Value = "Windows Server 2012 R2" });
                            createOS.Add(new SelectListItem { Text = "Windows Server 2008", Value = "Windows Server 2008" });
                            createOS.Add(new SelectListItem { Text = "Andriod", Value = "Andriod" });
                            createOS.Add(new SelectListItem { Text = "Apple ISO", Value = "Apple ISO" });
                            createOS.Add(new SelectListItem { Text = "Linux Ubuntu", Value = "Linux Ubuntu" });
                            createOS.Add(new SelectListItem { Text = "Linux Centos", Value = "Linux Centos" });
                            #endregion

                            <div class="form-group">
                                @Html.LabelFor(model => model.ComputerOS, htmlAttributes: new { @class = "control-label mb-2 text-muted" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.ComputerOS, createOS, "--------------Select-------------  \u25BC", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ComputerOS, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            #region ViewBag
                            List<SelectListItem> createEquipment = new List<SelectListItem>();
                            createEquipment.Add(new SelectListItem { Text = "Desktop", Value = "Desktop" });
                            createEquipment.Add(new SelectListItem { Text = "Laptop", Value = "Laptop" });
                            createEquipment.Add(new SelectListItem { Text = "All-in-One (AIO)", Value = "All-in-One (AIO)" });
                            createEquipment.Add(new SelectListItem { Text = "Copier Machine", Value = "Copier Machine" });
                            createEquipment.Add(new SelectListItem { Text = "USB Device", Value = "USB Device" });
                            createEquipment.Add(new SelectListItem { Text = "Numpad USB Device", Value = "Numpad USB Device" });
                            createEquipment.Add(new SelectListItem { Text = "HDD/SSD", Value = "HDD/SSD" });
                            createEquipment.Add(new SelectListItem { Text = "CCTVs", Value = "CCTVs" });
                            createEquipment.Add(new SelectListItem { Text = "IP Phone", Value = "IP Phone" });
                            createEquipment.Add(new SelectListItem { Text = "Server", Value = "Server" });
                            createEquipment.Add(new SelectListItem { Text = "NAS (Synology/QNAP)", Value = "NAS (Synology/QNAP)" });
                            createEquipment.Add(new SelectListItem { Text = "Machine", Value = "Machine" });
                            #endregion

                            <div class="form-group">
                                @Html.LabelFor(model => model.EquipmentType, htmlAttributes: new { @class = "control-label mb-2 text-muted" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.EquipmentType, createEquipment, "--------------Select-------------  \u25BC", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EquipmentType, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <button id="registerButton" type="submit" class="btn btn-primary">Register New Hardware</button>
                                </div>
                            </div>

                            //Pop-out Confirmation Message
                            <script>
                                    document.getElementById("registerButton").addEventListener("click", function (event) {
                                        event.preventDefault(); // Prevent the form from submitting immediately
                                        if (confirm("Are you sure you want to register?")) {
                                            // User clicked "OK", so submit the form
                                            document.forms[0].submit();
                                        } else {
                                            // User clicked "Cancel", so do nothing
                                        }
                                    });
                            </script>
                        }
                    </div>
                        </div>
                        <div class="text-center mt-5 text-muted">
                            Copyright &copy; 2023 &mdash; Yamazaki Mazak Singapore Pte Ltd
                        </div>
            </div>
        </div>
    </div>
</section>

SE Project/Views/Assets/GetHardwareAssets.cshtml
@model List<SE_Project.Models.HardwareViewList>

<div>
    <br />
    <h2>Hardware Assets Record</h2>
    <hr />

    <div class="table">
        <table class="EmployeeTable table table-bordered table-hover">
            <thead>
                <tr>
                    <th>IP Address</th>
                    <th>Computer Name</th>
                    <th>Equiptement Type</th>
                    <th>Full Name</th>
                    <th>Office</th>
                    <th>Department</th>
                    <th>Condition</th>
                    <th>Computer Status</th>
                    @if (Session["UserRole"].ToString() == "Admin")
                    {
                        <th></th>
                    }
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                                <tr>
                                    <td>@item.IpAddress</td>
                                    <td>@item.ComputerName</td>
                                    <td>@item.EquipmentType</td>
                                    <td>@item.FullName</td>
                                    <td>@item.Office</td>
                                    <td>@item.Department</td>
                                    <td>@item.Condition</td>
                                    <td>@item.ComputerStatus</td>
                                    @if (Session["UserRole"].ToString() == "Admin")
                                    {
                                        <td><a class="btn btn-success btn-sm" href="@Url.Action("EditHardwareAssets", "Assets", new { employeeID = item.EmployeeID })"><i class="fa fa-pencil"></i> Edit</a></td>
                                    }
                                    </tr>
                        }

                    }
                }
            </tbody>
        </table>
        @section scripts{
            <script src="~/Scripts/bootstrap.bundle.min.js"></script>
            <script src="~/Scripts/datatables.min.js"></script>
            <script>
                $(document).ready(function () {
                    $('.EmployeeTable').DataTable()({
                        // Set number of records to display per page
                        'pageLength': 10,
                        // Enable search functionality
                        'searching': true,
                        // Enable filtering functionality
                        'filtering': true,
                        language: {
                            "emptyTable": "No Data Found, Please Click on <b>Create Computer</b> from Dropdown Computer List"
                        },


                        order: [[5, "asc"]]

                    });
                });
                
            </script>
        }
    </div>
</div>